/drop
/read-only       server/modules/__init__.py
/read-only       server/modules/data_types.py
/read-only       server/modules/llm_models.py
/read-only       server/modules/openai_llm.py
/read-only       server/modules/tools.py
/read-only       server/server.py
/read-only       server/tests/__init__.py
/read-only       server/tests/llm_modules_test.py
/read-only       server/tests/openai_llm_test.py
/read-only       server/tests/server_test.py
/read-only       server/tests/tools_test.py
/read-only       server/utils.py
/add       src/App.vue
/add       src/apis/autocompleteApi.ts
/add       src/apis/toolCallApi.ts
/add       src/assets/vue.svg
/add       src/components/multi_autocomplete/ToolCallInputField.vue
/add       src/components/multi_autocomplete/ToolCallNotesTab.vue
/add       src/components/multi_autocomplete/ToolCallTab.vue
/add       src/components/multi_autocomplete/ToolCallTable.vue
/add       src/components/multi_tool_call/AutocompleteTab.vue
/add       src/components/multi_tool_call/DevNotes.vue
/add       src/components/multi_tool_call/MultiAutocompleteLLMTable.vue
/add       src/components/multi_tool_call/PromptTab.vue
/add       src/components/multi_tool_call/RowActions.vue
/add       src/components/multi_tool_call/UserInput.vue
/add       src/main.ts
/add       src/pages/AppMultiAutocomplete.vue
/add       src/pages/AppMultiToolCall.vue
/add       src/stores/autocompleteStore.ts
/add       src/stores/toolCallStore.ts
/add       src/style.css
/add       src/types.d.ts
/add       src/vite-env.d.ts
